Feature/contacts
Godden13/WhatSappWebb-Clone pull request #19
Opened 2023-06-08 14:21 UTC by kadjialan

design of contacts bar and message environment

2023-06-09 09:48 UTC, Godden13 requested changes
I see you deleted the index.tsx file from the main route. This is an important page which is necessary to the way our project is setup since that is the index route

2023-06-09 09:55 UTC, kadjialan commented
> I see you deleted the index.tsx file from the main route. This is an important page which is necessary to the way our project is setup since that is the index route
it hasn't been deleted. you have it inside the pages folder found in the app folder

2023-06-09 11:05 UTC, MALWICK approved these changes

2023-06-11 20:03 UTC, Godden13 approved these changes

2023-06-11 20:04 UTC, merged